import type { Summary } from "@/lib/types";

const GENERATED_BY_LABEL: Record<Summary["generated_by"], string> = {
  seed: "seed",
  llm: "AI",
  heuristic: "heuristic",
};

export function OverviewTab({ summary }: { summary: Summary | null }) {
  if (!summary) {
    return <p className="p-4 text-sm text-muted">No summary yet.</p>;
  }

  const paragraphs = summary.overview.split("\n\n").filter(Boolean);

  return (
    <div className="space-y-4 p-4">
      <div className="space-y-3">
        {paragraphs.map((p, i) => (
          <p key={i} className="text-sm leading-relaxed text-foreground">
            {p}
          </p>
        ))}
      </div>

      {summary.keywords.length > 0 && (
        <div className="flex flex-wrap gap-1.5">
          {summary.keywords.map((k) => (
            <span
              key={k}
              className="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-medium text-brand-700"
            >
              {k}
            </span>
          ))}
        </div>
      )}

      <p className="text-xs text-muted">
        Generated by: {GENERATED_BY_LABEL[summary.generated_by]}
      </p>
    </div>
  );
}
